#!/usr/bin/env bash

set -euo pipefail

FUNCTION="ATXX"
SUB_FUNCTION="ATXX_DIAG"
MODULE="ATXX_DIAG_CTL"

#
# CODE_HEMS
#

mkdir -p "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE"

touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}.c"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}.h"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_compiler_log.txt"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_static_analysis_report.txt"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_sil_results.txt"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_certification_report.txt"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/trace_links.csv"
touch "HEMS/CODE_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/code-manifest.yaml"

#
# MOD_HEMS
#

mkdir -p "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE"

touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}.slx"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_dictionary.sldd"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_interface.xlsx"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_variant.xlsx"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_stimuli.mat"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_calibration.html"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_analysis_report.txt"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_east_report.pdf"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_delivery_package.zip"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_sof_reference.txt"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_mdt_reference.txt"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/trace_links.csv"
touch "HEMS/MOD_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/module-manifest.yaml"

#
# SPEC_HEMS
#

mkdir -p "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE"

touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_spec_source.xml"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_spec_document.pdf"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_comparison_report.txt"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_history_log.txt"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_crs_interface.xml"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_sdt_reference.txt"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/${MODULE}_technical_fact_reference.txt"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/trace_links.csv"
touch "HEMS/SPEC_HEMS/$FUNCTION/$SUB_FUNCTION/$MODULE/spec-manifest.yaml"

echo "Created:"
echo "ATXX -> ATXX_DIAG -> ATXX_DIAG_CTL"